package com.himanshuProjects.disaster_damage_assessment_portal.enums;

public enum AuditAction {
    REGISTER,
    LOGIN,
    LOGOUT,
    CREATE_REPORT,
    UPDATE_REPORT,
    DELETE_REPORT,
    ASSIGN_OFFICER,
    COMPLETE_ASSESSMENT,
    UPDATE_ASSESSMENT,
    CREATE_COMPENSATION,
    APPROVE_COMPENSATION,
    REJECT_COMPENSATION,
    UPDATE_PAYMENT_STATUS,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    UPDATE_ACCOUNT_STATUS,
    SUBMIT_FEEDBACK,
    MARK_NOTIFICATION_READ
}
